version: "3.7"
services:
  nuxt:
    build:
      context: .
    container_name: web3d-frontend
    restart: "no"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: bind
        source: ./.docker-compose-volumes/node_modules
        target: /app/node_modules
        volume:
          nocopy: true
      - type: bind
        source: ./.docker-compose-volumes/nuxt
        target: /nuxt
        volume:
          nocopy: true
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
